### ISSUE TITLE
Tokio 0.2 support and maintenance 

### ISSUE THREAD

**Issue by tekjar** [quininer/tokio-linux-zio#4]
Hi. I'm looking for zero copy io like sendfile and splice on top of tokio 0.2. Does this repo work with tokio 0.2 and futures 0.3?

**Comment by quininer** [comment]
This library is currently deprecated. I initially wanted to use it with ktls, but due to the complexity of ktls and zero copy netowrk, I think this is not ideal.

**Comment by tekjar** [comment]
Ok Thanks :)

**Comment by jeromegn** [comment]
Did non-network zero-copy futures such a Splice work well? I'm thinking of translating these to tokio 1
